<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="UC.css">
<script src="UC.js"></script>
</head>

<body>

  <div class="title">
  <h1>Universities of California List<h1>
    </div>

<div class="container">

    <button class="btn">UC Berkeley</button>
  <img src="https://cdn-images-1.medium.com/max/2400/1*hQDoZXoVndvO5l_94obflA.jpeg" alt="Snow" style="width:32%;">

<button class="btn">UC Davis</button>
    <img src="https://www.ucdavis.edu/sites/default/files/styles/ucdedu_slideshow/public/image_gallery/20120928_tercero_120.jpg?itok=MDpr27Qm" alt="Snow" style="width:32%;">

<button class="btn">UC Irvine</button>
      <img src="http://d21gd0ap5v1ndt.cloudfront.net/web02/img.php?src=/images/members/UCI-campus-668x367.jpg&site=gccwater&width=920&height=518&crop" alt="Snow" style="width:33%;">

      <div class="LA">
        <img src="https://luskinconferencecenter.ucla.edu/wp-content/uploads/2018/03/Blog_Luskin.jpg" alt="Snow" style="width:32%;">
        </div>
        </div>

<!-- <h2> UC Irvine</h2>
<h2> UC Los Angeles</h2>
<h2> UC Merced </h2>
<h2> UC San Diego</h2>
<h2> UC Santa Barbara</h2>
<h2> UC Santa Cruz</h2>
<h2> UC Riverside</h2> -->







    <!-- <div class="row">
  <div class="column">
    <img src="https://cdn-images-1.medium.com/max/2400/1*hQDoZXoVndvO5l_94obflA.jpeg">
  <button class="btn success">UC Berkeley</button>
    <img src="https://www.ucdavis.edu/sites/default/files/styles/ucdedu_slideshow/public/image_gallery/20120928_tercero_120.jpg?itok=MDpr27Qm">
    <button class="UCD">UC Davis</button>

    <img src="http://d21gd0ap5v1ndt.cloudfront.net/web02/img.php?src=/images/members/UCI-campus-668x367.jpg&site=gccwater&width=920&height=518&crop">
    <button class="UCI">UC Irvine</button>
    <img src="https://luskinconferencecenter.ucla.edu/wp-content/uploads/2018/03/Blog_Luskin.jpg">
    <button class="UCLA">UC Los Angeles</button>
  </div>

  </div> -->






</body>










</html>
